//User data
export const MY_PROFILE = 'MY_PROFILE'
export const MY_PROFILE_SUCCESS = 'MY_PROFILE_SUCCESS'
export const MY_PROFILE_ERROR = 'MY_PROFILE_ERROR'

//Edit user
export const EDIT_MY_PROFILE = 'EDIT_MY_PROFILE'
export const EDIT_MY_PROFILE_SUCCESS = 'EDIT_MY_PROFILE_SUCCESS'
export const EDIT_MY_PROFILE_ERROR = 'EDIT_MY_PROFILE_ERROR'

//Edit Status user
export const EDIT_MY_STATUS = 'EDIT_MY_STATUS'
export const EDIT_MY_STATUS_SUCCESS = 'EDIT_MY_STATUS_SUCCESS'
export const EDIT_MY_STATUS_ERROR = 'EDIT_MY_STATUS_ERROR'

//Authorization
export const AUTHORIZATION = 'AUTHORIZATION'
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS'
export const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR'

//Add an invitation
export const ACCEPT_INVITATION = 'ACCEPT_INVITATION'
export const ACCEPT_INVITATION_SUCCESS = 'ACCEPT_INVITATION_SUCCESS'
export const ACCEPT_INVITATION_ERROR = 'ACCEPT_INVITATION_ERROR'

//Refuse an invitation
export const REFUSE_INVITATION = 'REFUSE_INVITATION'
export const REFUSE_INVITATION_SUCCESS = 'REFUSE_INVITATION_SUCCESS'
export const REFUSE_INVITATION_ERROR = 'REFUSE_INVITATION_ERROR'

//Upload new avatar
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR'
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS'
export const UPLOAD_AVATAR_ERROR = 'UPLOAD_AVATAR_ERROR'

//Update friends list
export const UPDATE_FRIENDS_LIST = 'UPDATE_FRIENDS_LIST'
export const UPDATE_FRIENDS_LIST_SUCCESS = 'UPDATE_FRIENDS_LIST_SUCCESS'
export const UPDATE_FRIENDS_LIST_ERROR = 'UPDATE_FRIENDS_LIST_ERROR'

//Info friend
export const INFO_FRIEND = 'INFO_FRIEND'
export const INFO_FRIEND_SUCCESS = 'INFO_FRIEND_SUCCESS'
export const INFO_FRIEND_ERROR = 'INFO_FRIEND_ERROR'

//Delete a friend
export const DELETE_FRIEND = 'DELETE_FRIEND'
export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS'
export const DELETE_FRIEND_ERROR = 'DELETE_FRIEND_ERROR'

//Handle Page
export const HANDLE_PAGE = 'HANDLE_PAGE'
