--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/31/2019 6:11:01 PM
-- Server version: 5.5.5-10.4.6-MariaDB-1:10.4.6+maria~bionic
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS voispy_prototype;

CREATE DATABASE IF NOT EXISTS voispy_prototype
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE voispy_prototype;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  passwrd TEXT NOT NULL,
  phone VARCHAR(255) DEFAULT NULL,
  bio TEXT DEFAULT NULL,
  company VARCHAR(255) DEFAULT NULL,
  friends_list TEXT DEFAULT NULL,
  verified TINYINT(1) DEFAULT NULL,
  saltKey TEXT DEFAULT NULL,
  activated TINYINT(1) DEFAULT NULL,
  status ENUM('Online','Offline','Away','Busy') DEFAULT 'Offline',
  role ENUM('admin','users') DEFAULT 'users',
  display_name VARCHAR(255) DEFAULT NULL,
  nbConnect INT(11) DEFAULT NULL,
  invitations TEXT DEFAULT NULL,
  avatars VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 243,
AVG_ROW_LENGTH = 787,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `email` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX email(email);

--
-- Create table `chat`
--
CREATE TABLE IF NOT EXISTS chat (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Participants TEXT DEFAULT NULL,
  Room_name VARCHAR(255) DEFAULT NULL,
  Notif TEXT DEFAULT '\'\'',
  Admin TEXT DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 858,
AVG_ROW_LENGTH = 222,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'Adelin', 'ARNOU', 'adelina.bhsoft@gmail.com', 'e901e0a3deedbedcd8232b11eb06c5f79814395194cfcb40f68eaf0bdaf81cd587f5fcd2a8badfcb9f7a63c86e0870c3fbd3553ba8eda338febb80458e7c2ef2', '123456', 'Hi!', 'BHSOFT', '26,57,27,136', 1, '16627fed1053a497', 1, 'Offline', 'admin', 'Adelin_ARNOU', 1078, '174', '7b9d278cebdffc48a9be6b1a0d797a5d_Arnou_Adelin.jpg'),
(2, 'Corentin', 'CALBERT', 'corentin.alb@gmail.com', 'e8d71c4a23d0779fb89a2869f56a72d09400bd37ec4d06a9ca5f969ad590a0604cb1499439b19a4b6884629d112823065f4abf04247464f4459c075c75413f03', '0677777777', 'Salut je m''appelle Corentin', 'BHSOFT', '57', 1, 'b9add434c4fa5959', 1, 'Offline', 'users', 'Coren', 206, '1', 'Anonyme.jpeg'),
(25, 'Quan', 'LE', 'quanhoang.bhtech@gmail.com', '70c7aabad80e1514ea0a4e3aebb1996cb72e0244992d6bd6c521174b18eba57f3b14cafef69533818325d795f4ada5fd8b4691350963a4ee1006136fd5136275', '437951676', NULL, NULL, '', 0, '2b92cf4807ec6b81', 1, 'Offline', 'admin', 'Quan_LE', 2, '58,157', 'Anonyme.jpeg'),
(26, 'Pac%C3%B4me', 'Gallais', 'gallaispacome@gmail.com', 'ef4f108f8f88d6bf5ecee08e9d122cb781fc2d0c7b5ba0d3aae64160888360ba8a814910afd366f80b607a5b5f81f350b3261f7ce43e0e5fa85abf9cea317654', '0684345433', 'Salut%20%C3%A0%20tous', 'BHSOFT', '1,27,57', 1, '2699997c1f323c68', 1, 'Online', 'admin', 'Pacroute53', 425, '', '77fb858bde60b851fecff1133cacdeba_32472030_2418872314805484_8550468786057117696_n.jpg'),
(27, 'C%C3%A9dric', 'LECOUILLARD', 'cedric.lecouillard35@gmail.com', 'e143f94b6452b721c22a8d4be3ffe452d02f38e97ec0d582e90c615e5879aa4d4a14541b67dcd9f4da3a3c152dd76ffd48e20254d9a053744be2c7cdf691a1ce', '0673338906', 'salut', ' BHSoft ', '57,1,26', 1, '5e7533baf08cb025', 1, 'Offline', 'admin', 'C%C3%A9dric_LECOUILLARD', 601, '', '3b2bd8a3c095c828eafd4a7450d51d30_Lecouillard_cedric.jpg'),
(57, 'Corentin', 'ALBERT', 'calbertisn@gmail.com', 'b6a98d29374968f6a4898945433bd37507f3137b288eb8081b4c6b2f8918db6e1cc3e99c2e2afb9028f8560b5f54a210013723405aef7ad155226cfab6b698bb', '0675457862', 'Hi,%20my%20name%20is%20Corentin%20and%20I%20am%20working%20for%20BHSoft%F0%9F%98%85', 'BABA', '2,27,1,26,149,155', 1, 'c9e7016a473f0659', 1, 'Online', 'admin', 'Coczer', 976, '174', '3d890c89dbcfd630464d7b2eb5c8f1e7_Corentin ALBERT.jpg'),
(58, 'Quan', 'LE', 'quanhl@bachasoftware.com', 'dc44fe0753f29ca2a5fc28448e83379067dd2ec8b1acafa9ebe25c41c8da8b81c2147ba8924203da5acc7487acd18d10825d30c300d3208ca857807cf12b5141', '437951676', NULL, NULL, '124,126,157', 1, '8d94a570aa889d05', 1, 'Online', 'admin', 'Quan_LE', 34, '', 'Anonyme.jpeg'),
(118, 'Anh', 'HOANG', '69anh96@gmail.com', '7fd1d16499028a3647f60ab7f4e283257f600ae3e142f7695060f98ef79b170c0c2e22fc815c9f45a974bef51ec5dfcd6375d927f09fb88f7b963627dcbc9c4e', '0943088526', NULL, NULL, '129,161', 1, '14254aaf0afac627', 1, 'Offline', 'users', 'Hello Halo', 22, '', 'Anonyme.jpeg'),
(124, 'Quan', 'LE', 'quanhoang.bhtech+1@gmail.com', '892334bab8be3cce99970880185e5f87b078810d192d86b88ab52123ebb87738fb8bcdc691ce9cf9505478130065ddfbcbd208bf328e692e02537a1e3a895069', '0437951676', NULL, NULL, '58', 1, 'f7a98f702cf065d7', 1, 'Offline', 'users', 'Quan', 3, '', 'Anonyme.jpeg'),
(126, 'Tran%20Vu', 'Viet%20Anh', 'anhtvv.bhsoft@gmail.com', 'b3d1b965e9271872b89730128b89ffba5c4d3b9c5d7b0443cb567c6db443691ea0fcc73ef1053577721d57cdd6819e2aa80cbbd69e4199145ef6b28e80f36567', '0906689199', 'Kh%C3%B4ng%20ph%E1%BA%A3i%20Null', 'BHSoft', '58,157,129', 1, '4054a1023ffaf2d8', 1, 'Offline', 'admin', 'Viet%20Anh', 22, '', '1f69856ada48cbfdfc37ecdfffe3268d_20181129_104716.jpg'),
(127, 'Hoàng', 'ANH', 'anhdh.bhsoft@gmail.com', '26c0c740790fc871c4edc2c4a29f28cd20438436e5422e8629bce87ae5bb6fc9cd955ce77dbbe766b5748e2cda919aadd03c2dd79ddea1a86f02ac9f07d1767f', '0943088526', NULL, NULL, '132,130,', 1, 'cda3152ca6eecbe1', 1, 'Away', 'users', 'Beerus sama', 23, '129,192,126,171', 'Anonyme.jpeg'),
(128, 'Hong', 'NGOC', 'ngoclth@bachasoftware.com', '7c761a2d7b09865194da5b57baf335d3782546c15d02f466f1eaaf6ddee1b375f20270c93f2b2631553e7b431f2e1513a1fd8d3c417af0b0ee54fda8a439d938', '0901', NULL, NULL, '', 0, 'd580593dbb0e39ec', 1, 'Offline', 'admin', 'Hong Ngoc', 1, '158,157,162,161,184,186,192,126,171', 'Anonyme.jpeg'),
(129, 'Hong', 'Ngoc', 'ngoclth.bhsoft@gmail.com', '8690ea17fb2f4676cd4c675b246dfe05daea59542ea8124246963efd53174524514244eaaa8362c3872abcecb887754606a4c739cd951f5c92674824b63b1151', '(453) 463-4635', 'My%20biod', 'BhSoftware', '133,184,118,126,195,192,157,188', 1, 'c55c8b55cffb9543', 1, 'Offline', 'admin', 'hong%20Ngoc', 145, '162,179,216', 'ec5e14d7f80d9154b9522e1068a2760a_Icon.PNG'),
(130, 'Ahihi', 'BHIHI', 'danghoanganh96@gmail.com', 'bd18c2e1a09b3df3f6c2aafe371edf3ff998ce3f79c6aace137f1362349fc1d507d272a5ff6af4e5048d0be000d2e3c73e8e3b634ebc655e85aaf00f6f2ca373', '0943088526', NULL, NULL, '127', 1, '06e3511ed284709d', 1, 'Online', 'users', 'zeno sama', 31, '192,188', 'f1a681d109dcf4e291e7caa2c4360850_Screenshot_9.png'),
(131, 'Nguy%E1%BB%85n', 'Thu', 'thunt.bhsoft@gmail.com', 'edf11b4ba52b1a0e3f261d9e5060e9537d4ff12691b4a41c585e0c8615f4433bf4e33ab36b85384c9a231b1ffa6160adf60eaef8f4873c29b16ca492f4e8b4c4', '(123) 445-5677', 'BH', 'Bac Ha Software Co., Ltd.', ',132,132,', 1, '6e90506ff2d8b1ba', 1, 'Offline', 'users', 'BHsoft', 60, '185,186,129,184,192,126', '9615d33d6bb5e7dec268210378a3bf6f_20190110091748294.8B3A6B654C6D447DCD15D8178D4B696F.png'),
(132, 'Nguy%E1%BB%85n', 'Thu', 'thunt52@wru.vn', 'c0e5dba2d61ce4d7beac17a5bb5317b323071a7780497fcf28706c9d6bb57c15612fef10cee9cb8498079f316fe2e9121da7b516c2e51f11f3f7113699117d38', '(123) 455-6677', '%20%20BH', 'Bac Ha Software Co., Ltd.', '131,127,133,170,185', 1, '0ddbb74900de1dc4', 1, 'Offline', 'users', 'Thu', 115, '188,129,184,192', '95ee25c7382e910a26cbf67726e4db08_Image from iOS.jpg'),
(133, 'You%20are', 'Umasou', 'tester.bhsoftware@gmail.com', '5444d4bf8393aadaea53208e8b59d6840bd72094a9045215da9735fd5bfab53f52db81a739b1249ddf31936c4d2a4b462d83701636c863ff5e227251e5a6bf52', '0888888888', ':)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))', 'BHsoft', '129,132', 1, '8a8b97e51ce8a29e', 1, 'Offline', 'users', 'Umasou.', 23, '184,185,186', '7ef363ba9be9a82f6714db84c3294818_IMG_0987.jpeg'),
(134, 'Ahihi', 'BHIHI', 'aloalo0943@gmail.com', '1a9f042ebd59edd4c91b2d4c0c2dd75c51afd2994ac36d3b2c9ced2c670bac617e1372411a69fb66518556f0800a74534cf8d2ab076301606e4f9996f51dc92f', '123123', NULL, NULL, '', 1, 'fea9afb4b70bcf73', 1, 'Online', 'users', 'Songoku', 49, '127', 'Anonyme.jpeg'),
(135, 'Hakai', 'HAKAI', 'aloalo0943088526@gmail.com', '8b289498c44a75aa729b6a7250e0fa5d5a638dd1e5565dd237f0856be082818e7fe8e1a53c27f8cbb0266bf8c65ae55af3f69716a7f97388c6a49adaf522785d', '@@@', NULL, NULL, '', 1, '0c580339d124a4d1', 1, 'Offline', 'users', 'Okaishin', 4, '', 'Anonyme.jpeg'),
(136, 'aa', 'aa', 'adelin.85130@gmail.com', '69a4afb59e79ff3df0d8cd5ab86028b02b61a3ea5f44e5d7a25b4432e512698267358a4ebad31d49d9131d3c01720123a9b792945b6ca7e5e9c1e797c0f45f5c', '125336', NULL, NULL, '1', 1, 'a281a9170c5b2be2', 1, 'Online', 'users', 'aa', 13, '', 'Anonyme.jpeg'),
(145, 'Phan ', 'Thuy', 'thuyphan.bhtech@gmail.com', 'ba696a5098ce1220f4261085edd6bb5bb7108e186d14562ba6903b5919758fd85c48425148edaee796f2e3a832835f28c97a48f0a7d62fea64a3b4d628591d01', '1234567899', NULL, NULL, '', 1, '028b80de99d9c9c2', 1, 'Online', 'users', 'Ngao', 10, '129,133,170', 'Anonyme.jpeg'),
(149, '%E1%BA%AF%E1%BA%AF%E1%BA%AF%E1%BA%AF%E1%BA%AF', '%E1%BA%AF%E1%BA%AF%E1%BA%AF%E1%BA%AF%E1%BA%AF%E1%BA%AF', 'korent1.a@live.fr', 'c24b5df36d097107b756eec8aa6b933135debf1fa25a705c79c66eb8abc933d9f3425d6b178192987bd49e78525c479b52fbfeea44d353f6030bcb2729d92c9c', '0675457862', NULL, NULL, '', 1, 'b67b79852417b6e0', 1, 'Online', 'users', '%E1%BA%AF%E1%BA%AF%E1%BA%AF%E1%BA%AF%E1%BA%AF%E1%BA%AF', 16, '', 'Anonyme.jpeg'),
(153, 'C%C3%A9dric', 'Lecouillard', 'cedric.lecouillard@reseau.eseo.fr', 'a0bcc8d0ebe69d0f95c6d736b69d729676433d266d9a9a718959decd4d088054e1bf138fe248728ffbdc04721498f3abadb647abda9b30f1fe922ad3dd79b5f2', '0101010101', NULL, NULL, '', 1, '43c6b89e01aa1b2c', 1, 'Online', 'users', 'cedo', 5, '', 'Anonyme.jpeg'),
(155, 'Corentin', 'Albert', 'corentina.bhsoft@gmail.com', '335085e7a917d63edf5c1db81a8a6112c7a4c2eb9edc34d254c2892ef39600875dc2c5022c0023aec3c97a14352a265638fc98a4d813eec5275dbd6946207173', '0675457862', 'Hello%20my%20name%20is%20Corentin%20!', 'BHSoft', '57', 1, '2ece1ef33ebf7c90', 1, 'Offline', 'users', 'CorentinA', 3, '174', '6021768a9ccb20cb884c5e9f6171840c_Corentin ALBERT.jpg'),
(156, 'Ngoc', 'Nguyen', 'ngocnb.bhsoft@gmail.com', 'd1d76cd844e59c83b424ae9d4d081e6690e8641cc85886b35618b2f5c576c0573c047675b0f7173ef53125990cb458771f6bb1af5a3ed2cc332a965ff523372a', '0829565147', NULL, NULL, '', 1, '19311ba97d2f0c88', 1, 'Online', 'users', 'Moc', 11, '184,186,192', 'Anonyme.jpeg'),
(157, 'Minh%20Quan', 'Tran', 'quantran.bhtech@gmail.com', '0e15e83352a0cbe6c3b3abeb4e160c166cd15857e7709733d6ac151a71ef56fbcc0e13698bdff313324a7169cdbe7363c576a9286cde0a5254bde05ead1a0b98', '0374099119', 'Quan''s%20bio', 'BHSoft', '58,158,126,129,195', 1, 'b8eb9ddabfb3d009', 1, 'Offline', 'users', 'quantr.bhtech', 85, '184', 'Anonyme.jpeg'),
(158, 'quang', 'nguyen', 'quangnd.bhsoft@gmail.com', 'c76fcf58e798524411e94e60f6cc1868d4f7be271573983d4837676ef780e0b140de5639c666e4ddec9ed5966b2b46fbaba618cf66bbc045836eb132250f6293', '1321654987', '234234234234', '123213213 345 345 35 34', '157,162', 1, '8e77d40a51ef152d', 1, 'Offline', 'admin', 'Quang', 115, '161,126', 'Anonyme.jpeg'),
(159, 'fdsfsdfs', 'fdsfsdf', 'fdsfsdfs@fsdfsdfs', 'a23861443e25a713e75cfdd3c866f0aa29ecbc3acae584c3bddc7756fe4ef5f9b7160a5d0f15991a70c89b847eb21b29afcc5d05ff6eee5a276f24f07e3327ac', '5323235235', NULL, NULL, '', 0, 'd9046e77b1b9c106', 1, 'Offline', 'users', 'fdsfsdf', 0, '', 'Anonyme.jpeg'),
(160, '%C3%B4k9', 'ia9sd9a', 'sadsd@xn--daw-dla', '1acec1fe5888140fa10dcb5e87c50457116cc71e604c72738b635e5db99675b3f682f66a6f8d3054efaa7fea99f0d02a4ed9d5fe10120a6bd197dc342825b49f', '1111111112', NULL, NULL, '', 0, '2c3ff635c04f8cbb', 1, 'Offline', 'users', '%C3%A1cfa', 0, '', 'Anonyme.jpeg'),
(161, 'C%C6%B0%E1%BB%9Dng', '%C4%90%E1%BA%B9p%20zai', 'Cuongdv.bhsoft@gmail.com', 'c0892b273429f905155e6a72e1e8a0d55f59befa178b2e39c9aca6e437eb484d90f96c05a20ea6374bdc90634e88e7a845969d8644e917c1f5718c81f7ec9f65', '1111111111', '%20%201', '  1', '162,118', 1, 'a6c8cb6e83d65aa3', 1, 'Online', 'users', '%20%20C%C6%B0%E1%BB%9Dng%20Flyy', 69, '', '9d3ef1159519f93bdb110e8edf548376_avt.jpg'),
(162, 'C%C6%B0%E1%BB%9Dngaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', '%C4%90%E1%BA%B7ngaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'dangvancuong.ddt9@gmail.com', 'f23410d144af1d41bb9290fb1c7ed3304a4982d87e9694628e5a5e34a2cfa1e3a008b1247cafb3cbec11981d01217202b11da192f44211f3512a2d6940d0226c', '0000000000', 'nullaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', '161,158', 1, '88081a86b5fa5be2', 1, 'Online', 'users', 'C%C6%B0%E1%BB%9DngFlyaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 29, '', '92b8eb1e12f64500c8c6842cdeba9f77_logo.jpg'),
(163, '%C3%B4k9', 'ssss', 's@sdasd', '035995493f1e55818d8a7cd7909f1b17d8803d9c643cd54c659c3d0f91b8cd77758f95b35e349ce76abc6d1abb0581b9dc6e5287376d248c4e3bb593821361f6', '1111111112', NULL, NULL, '', 0, 'fcde62e4e54e12f3', 1, 'Offline', 'users', 'aaaa', 0, '', 'Anonyme.jpeg'),
(164, 'aaa', 'ssss', 's@sdasd.com', '2163a928321b4546b020ae763c4d21f4e53ce87262f47e0d36c8727b28917a1d576e392d0396362ecc764320133d32af059550c9afd9d8bdf28a58bbc02a0217', '1111111112', NULL, NULL, '', 0, 'ad9d2f9fc3fe80af', 1, 'Offline', 'users', 'anhs', 0, '', 'Anonyme.jpeg'),
(165, 'aaa', 'ssss', 's@gmail.com', '58030fe745f00f4588630b39b4282fa3bc9b77fdc59e447a97ceb7202de4d8de29246f5b527e93e6ff98a7cdf0a3254f5e01ad7f783b8c72a43b4a69122dfc41', '1111111112', NULL, NULL, '', 0, 'c132a975b13a1150', 1, 'Offline', 'users', 'aaaaaaaa', 0, '', 'Anonyme.jpeg'),
(166, '123123dsfgdsfgdfsgdfsg', '123213213dfsgdfsgdfsgdfsg', 'test@gmail.com', 'c131d44e00aad37d281d6a96decb11c1cc057e5794cbf55d9e9e0cf84149a829c8b7142759a36607c936b9f5d9c03eb1533a956b086c8c355a712c1178d8e22c', '0321654654', NULL, NULL, '', 0, '16d3f5854aa5f275', 1, 'Offline', 'users', '12321444444sdfgdsfgdfsgdfsgdfsgdfsgdfsgdfsgdfgdsgdfsgdfsgdfsgdfsg', 0, '', 'Anonyme.jpeg'),
(167, 'd%C3%A2sd', '%C6%B0dasd', 'aasdasa@gmail', '1c57a45611954397cc80b570cb944f45652b44ec3e3f59d0f0830e812271960d358c42d79a723c2e384576ddcc4182103c821e5fa0f1df0f9118c2bfef8895f0', '1111111112', NULL, NULL, '', 0, '8efe2d4783b36c25', 1, 'Offline', 'users', 'uawdas', 0, '', 'Anonyme.jpeg'),
(168, '%C3%A1dasd', '%C4%91%E1%BB%A9a', 'asdasd@dsd', 'd1fc12247d25e93e423ff8f95b52fcdfcb7f7908182a5309e802bb5d18cf190d36efc7603eb3b913d1685a2fde501d931686b36160be17387c39288ab719c800', '1111111112', NULL, NULL, '', 0, '68eeda273863b6b1', 1, 'Offline', 'users', '%C3%A1das', 0, '169', 'Anonyme.jpeg'),
(169, 'user', '3', 'trungtong.bhtech+003@gmail.com', '7178cd93b9655e0e58a07bba3fdbbd44458c981d4c63f4bdd1556e8ab13642e5ca2bbe41c54259baef702d0a628089c578d55a744c861c40fd8c06bdf2d133c5', '0912611246', 'Hello%20world', 'BHSoft', '170', 1, 'f63c23fc9f4a8928', 1, 'Away', 'admin', 'user_3', 134, '192', '2fe7573a5f284f7a6244336ef33ebe76_Untitled-3.jpg'),
(170, 'user', '2', 'trungtong.bhtech+002@gmail.com', '29af09b8e24adfb08242aa8966b65d0e848cd4666571a1a6315b422751ddee9954e6af54121e9bc885232cd7e2e965354841a7fb0ed2eb7cba5be4c52a814ed3', '0912611246', 'Hello14', 'BHSoft', '132,169', 1, '473b3fd324f0578c', 1, 'Away', 'admin', 'user_23', 216, '', '54c77ec98e5758f87fade581ac512ea1_LivingRoom (1).PNG'),
(171, 'user', '1', 'trungtong.bhtech+001@gmail.com', 'd0b61d5dc80c81499a21fb4ee1c9b532fb7495c3877fb3b60e8e2039dd14523418f090e8f39a1025ccd050ef320e3e045ae69c74e1e7c28857b0eafae0ff6fa7', '(091) 261-1246', 'BH143', 'bh', '216,228', 1, 'da4c627bca2ccb69', 1, 'Away', 'admin', 'Quang%20Trung', 202, '', 'Anonyme.jpeg'),
(179, 'Test', 'M1', 'manhtv.bhsoft@gmail.com', 'b6c9c302d534c894fc71d662f4d42a54a0eea522b150182c67cf58875e4ad94470711ee990bebc0877d0fa7e32b1c102d04037ff40d396eeb3f567a13ae2a991', '0998765432', 'Manuian', 'BHSoft', '180,181', 1, '1bfb0d8e25953735', 1, 'Offline', 'users', 'TestM1', 45, '', '13e11de8e5dcb44d57a399d5a9d84b7f_1231231.jpg'),
(180, 'Test', '123', '123456khj001@gmail.com', '904f5888ba6e35a3ce751ef87e8701b3cf02b81ef86e762c16ab3ea88c7e668ee8b067dce432d33ed64d43cb301cc99575054ca98e7237893103c460c2237dad', '0928131455', 'null11', '111', '179,181', 1, 'b983803179686315', 1, 'Online', 'users', '123456', 39, '', '6e8deeb5c0c056fa64fcfb5e4647a30d_24423235.jpg'),
(181, 'Manh', '3', 'manhtv.tn99@gmail.com', '199df1fdb656b14d116bb83697bbd91415de1a8154cacba641fc5bfbb9ac831a9344903a7491483b040f9cb132c44fb7c1346c623a257b9ed48688920c10ab38', '0987654321', NULL, NULL, '179,180', 1, 'fbcc6760a5dccbce', 1, 'Online', 'users', 'Manh3', 11, '', '09d2b62a76c76377000d1b05e6586349_24423235.jpg'),
(182, 'Nguyen', 'Thu', 'tester.bhsoftware+2@gmail.com', '244c50eedaa1c36eaf25887f1016f22a7e54a3320d7d16277d84b063b7d9fecb3a0b1a228d64631995298c29b690e317fb387a4b02c21cb6a24c405a2b7c2fb2', '1234555678', NULL, NULL, '', 1, 'a62224dcb3951b13', 1, 'Online', 'users', 'Thunt', 20, '', 'Anonyme.jpeg'),
(183, 'A', 'A', 'tester.bhsoftware+12@gmail.com', 'eb98a6e2784d1814ec598bd2e00d023c55859ca8c81f508083eb6ba43815a3aa77548d2d3817c7f6c2a4555071d5cb4be8ca8cbd991f1707fea532930ffef83e', '2345621212', NULL, NULL, '', 0, '46bbd88af87b28a3', 1, 'Offline', 'users', 'A', 1, '184', 'Anonyme.jpeg'),
(184, 'You%20are', 'Umasou', 'anhdh.bhsoft+1@gmail.com', 'bf0621a5c70af50b53fb3d98e1eeec80ad0b9d17daff3905e81c7486ffdf93231ce81289b40806a4597d9cd2047da27ebe01e4d8610374f16ac723be352d9a27', '0888888888', 'Done', 'BAC HA SOFTWARE CO., LTD.', '129,186,187', 1, '102e70980f295d55', 1, 'Offline', 'users', 'Umasou', 95, '', '0868132f02ac2d2f68a24914dfdbd557_Image from iOS (6).jpg'),
(185, 'Anh', 'Anh', 'anhdh.bhsoft+100@gmail.com', '6af794d499796d6cd9c9c051dbb289581ad88b37899b067e154efd2b3c528d78fb405b62ea05d41371472b3199ac71d7dab3763b0f048a9dc8de3c2794ed7911', '1231231231', 'null', '0800000000', '132', 1, '088fd07c7d51b643', 1, 'Offline', 'users', 'Anh%20Anh', 81, '184,192', '3c80b36bf08b90d127a0aca90f05e743_Image from iOS.jpg'),
(186, 'You%20are', 'Beerus%20Sama', 'anhdh.bhsoft+1000@gmail.com', '3f0b918e276fdcceb80959ad4dd5363319cd7394d5dbb71d0088e3be39b53ad663feb68e7c889f9e7e0ccaedbfc1e2a5487023b8f05ce2b2fa318a705b82b098', '0987654321', NULL, NULL, '184', 1, '5de9affb949375c5', 1, 'Offline', 'users', 'Beerus%20Sama', 7, '', 'cecccc0213e8eb3af72a78b45ea2270d_53202211_2293110974291981_8790487063389536256_n.jpg'),
(187, 'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq', 'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww', 'anhdh.bhsoft+50@gmail.com', 'add97f976f62658b348c126c574e5b70f2533cd8ab858f6a0943a9b1c0ff2e42e918d6bffcdab1e26c7ae7e6bf8a8caa8bbf785b850001de525615af99c1e265', '0888888888', 'null', 'BAC HA SOFTWARE CO., LTD.', '184', 1, 'c081fd277cf737c2', 1, 'Offline', 'users', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaa', 5, '', 'fb52019f2084218e4a72d659c03efa76_image (10).png'),
(188, 'Dang', 'Nguyen', 'dangnp.bhsoft@gmail.com', '093d0f7e1993798cc265e7d47cb5e8f35bbc639f220d2d492aec8cbbff93387b8b4d9592f5eb9537c693c0e4c4e88a0fb7cdc5b6674d0ee561d89d3fe586c2fb', '(088) 693-6892', 'Contrary%20to%20popular%20belief,%20Lorem%20Ipsum%20is%20not%20simply%20random%20text.%20It%20has%20roots%20in%20a%20piece%20of%20classical%20Latin%20literature%20from%2045%20BC,%20making%20it%20over%202000%20years%20old.%20Richard%20McClintock,%20a%20Latin%20professor%20at%20Hampden-Sydney%20College%20in%20Virginia,%20looked%20up%20one%20of%20the%20more%20obscure%20Latin%20words,%20consectetur,%20from%20a%20Lorem%20Ipsum%20passage,%20and%20going%20through%20the%20cites%20of%20the%20word%20in%20classical%20literature,%20discovered%20the%20undoubtable%20source.%20Lorem%20Ipsum%20comes%20from%20sections%201.10.32%20and%201.10.33%20of%20%22de%20Finibus%20Bonorum%20et%20Malorum%22%20(The%20Extremes%20of%20Good%20and%20Evil)%20by%20Cicero,%20written%20in%2045%20BC.%20This%20book%20is%20a%20treatise%20on%20the%20theory%20of%20ethics,%20very%20popular%20during%20the%20Renaissance.%20The%20first%20line%20of%20Lorem%20Ipsum,%20%22Lorem%20ipsum%20dolor%20sit%20amet..%22,%20comes%20from%20a%20line%20in%20section%201.10.32.', 'asdfasdzcxzxczxdfasdf', '192,129,195,228,189,237', 1, 'adac7aaf8b097d09', 1, 'Offline', 'users', '%C4%90%C4%83ng%201', 206, '', 'aea58362b8044429081b88f41a12931d_restaurant-araz.jpg'),
(189, 'Daniel', 'Nguyen', 'malauca012@gmail.com', 'd0905c3b10c96164403ddd1ceee40f9fdf28192e4124cc6f5296aadcfc941d1bf7a40626b6c0c974a7fd11f1b192399483b0f56eeaf9b2c441ea08695c800cd7', '0886936890', 'Lorem%20Ipsum%20is%20simply%20dummy%20text%20of%20the%20printing%20and%20typesetting%20industry.%20Lorem%20Ipsum%20has%20been%20the%20industry''s%20standard%20dummy%20text%20ever%20since%20the%201500s,%20when%20an%20unknown%20printer%20took%20a%20galley%20of%20type%20and%20scrambled%20it%20to%20make%20a%20type%20specimen%20book.%20It%20has%20survived%20not%20only%20five%20centuries,%20but%20also%20the%20leap%20into%20electronic%20typesetting,%20remaining%20essentially%20unchanged.%20It%20was%20popularised%20in%20the%201960s%20with%20the%20release%20of%20Letraset%20sheets%20containing%20Lorem%20Ipsum%20passages,%20and%20more%20recently%20with%20desktop%20publishing%20software%20like%20Aldus%20PageMaker%20including%20versions%20of%20Lorem%20Ipsum.', 'dasfsadd', '188', 1, 'fbcca27bac84231b', 1, 'Offline', 'users', '%C4%90%C4%83ng%202', 58, '', 'Anonyme.jpeg'),
(190, '45645', '456456', 'anhdh.bhsoft+10000@gmail.com', '3effbb4e6b34dd1bb310be479419f52324471fea31a1067840116715ba837d1274e3714947e6c88d70a8456766ec40bb8d284635df45445f536dac4adfd2b5e8', '5645645645', NULL, NULL, '', 1, 'c74411247e76379e', 1, 'Offline', 'users', '456456', 4, '', 'Anonyme.jpeg'),
(191, 'Dang', 'Nguyen', 'dasf@gmail.com', 'fbae3a843cf00a6b5b942af96c4dbeb51d1aac84404263168707655e1521f8dd9478b4cb411b160ffda291887a2ee13ddee6fdd4414bec179ca39f9f708ff762', '(111) 111-2322', NULL, NULL, '', 0, '80d37aeb672b8aff', 1, 'Offline', 'users', 'dasdas', 0, '', 'Anonyme.jpeg'),
(192, 'You%20are', 'Umasou', 'anhdh.bhsoft+0@gmail.com', '16519aab3a9ae8ac498e36a1f54dc269f778cda129256053bf17b52e758fcd3666059b27e0b4d6141c94776fe0c2c30493cd169c82aaef2f5caf828c20d1f9e0', '(123) 123-2131', 'nullkljlj', 'll', '193,188,195,129,196', 1, 'aad6cf5ac6a2e1e8', 1, 'Offline', 'users', 'bloblo', 67, '', 'aefc09d3b670b0a20565ef5eec34a418_image (3).png'),
(193, 'Nguyen%20', 'Thu', 'tester.bhsoftware+10@gmail.com', '9773488ade4f51c0d353b234a67299ec39bd38915efbd766c15ac8fced22601ee45e97c706a4a4a64b9c0587ae69fe72f54a304ee0cfa334685bcea39c76b516', '(123) 456-7888', NULL, NULL, '192,201,204,195', 1, '7730e9dc46b3be39', 1, 'Offline', 'users', 'Thunt.bhsoft', 17, '', '4b8e9f35d7ad0459a0ec3a4b532bce3c_1.jpg'),
(194, 'Hong%20', 'Ngoc', 'Ngoclth@qa.team', '1d2be2f4019d2a334061314c4a7d16cbf1c5a698be9f6e733b25e49a3f0ed6b786439b30f58d14578544080bb3309ed0ab9b88cf6507fe6e4d2c6193f5e5f1fc', '(453) 465-4654', NULL, NULL, '', 0, 'cf9f2f99a20ed0dc', 1, 'Offline', 'users', 'Hong%20Ngoc1', 1, '193', 'Anonyme.jpeg'),
(195, 'Nguyen', 'Giang', 'Giangnh@mailinator.com', '119e447f91458590ce940e68d5fbd22da7d4bda2c2ff9a18a41bf9d6d5ad10fe71953311386fd496b9fc390754fada922d9a843cebeda5bfa1fd04b8a7a98516', '(463) 465-4756', 'null', 'My company', '192,193,204,129,157,188,216', 1, '68d85bcdb78e6459', 1, 'Online', 'users', 'Giang%20Huong', 33, '218', '3f02eba792ee3c4530915478e5f0ce04_Nathen.PNG'),
(196, 'Osama', 'Biladen', 'anhdh.bhsoft+00@gmail.com', 'aa3aa95db7cd33a536b8a889956a66bbd929b6d29366e00d5ae6ae6b4c5ea8744532fbdf22e03584fd4351ba49d31cad921d557bf1e461be8ebfb26beaf07249', '(123) 123-1231', 'null', 'BAC HA SOFTWARE CO., LTD.', '192', 1, 'aee1443284e77543', 1, 'Offline', 'users', 'qqqqqq', 68, '', 'e7e88410e6da3ea5acfa7d7cd93a6d88_Image from iOS (6).jpg'),
(197, 'Nguyen', 'Nguyen%20', 'thunt@qa.team', '5c430b91c59a4f92f539643ff08e554e876be516546145c8779f99f4488b7bca58ad56d45ea768a770258a67c6c31217b70cd46d3f09b58368f6074e3a545d04', '(213) 243-4523', NULL, NULL, '', 0, 'da720f2aa4ded19c', 1, 'Offline', 'users', 'Helen', 0, '', 'Anonyme.jpeg'),
(198, 'Nguyen', 'Nguyen%20', 'thunt123@qa.team', '5ec455774835009d6de23ef50bd5cc54698d013cb6a8887f5783770c8ed53d50d77ca42b893eecda2f0152fd63d0306d2da79c9896239b1f9e071d90e162b221', '(213) 243-4523', NULL, NULL, '', 0, '24f3a517399e970c', 1, 'Offline', 'users', 'Helen1', 0, '', 'Anonyme.jpeg'),
(199, 'Nguyen', 'Nguyen%20', 'thunt132@qa.team', 'a6a3ee041cd84c07e12c7b2eb758ac9cbbf4abdd293ef1783ff459a70c93dad339f8f744a471eea055bf99410b579141df51b2261f79207af6d34358d67b5a47', '(213) 243-4523', NULL, NULL, '', 0, '36359e66395e03cf', 1, 'Offline', 'users', 'Helen2', 0, '', 'Anonyme.jpeg'),
(200, 'Nguyen', 'Nguyen%20', 'thunt1324@qa.team', 'd8743f0122ab441d06fec42192eecaa98174b6ded4a5f8ad3035f5e3273bd9aee76fe92a6c41a62a8b28bda35d869776cdd4bef2b62a3d89d977f9b53cf9b7c2', '(213) 243-4523', NULL, NULL, '', 0, '3e86e65d4da054bd', 1, 'Offline', 'users', 'Helen3', 0, '', 'Anonyme.jpeg'),
(201, 'Nguyen', 'Nguyen%20', 'thunt123@mailinator.com', 'c4bb597821f6907bff2eef47c07a9748a22d56a925fe0285fc85d10f07514b586de797d550f964ebd5a5a430bb3d45757b8b53448c8895f3d5ff963707cde809', '(213) 243-4523', NULL, NULL, '193', 1, '78912b2f1ede5e65', 1, 'Offline', 'users', 'Helen4', 6, '204', '6fb94d7d67c09c3059d6e19b88368a9b_2.jpg'),
(202, 'ABC', 'XYZ', 'anhdh.bhsoft+00000@gmail.com', '6c4ea53dba020b94c07a40248a68d05d3f27aa222b1b8f5fa9b551f8bad31432f9212a0292680e57ed7744e05fa5abeb705be6c14f77bd22a07f7bfda1c0781f', '(123) 123-1231', NULL, NULL, '', 1, '532c159333dbeb8c', 1, 'Offline', 'users', 'XXX', 4, '196,204', 'Anonyme.jpeg'),
(203, 'ABC', 'XYZ', 'anhdh.bhsoft+0000000000@gmail.com', '3a484b3549b163d500e98e4e0cb6dad8bbdfbd64c3fc861c5f42d42f6d5deccb2ba8758f7781558f35e5f86f649f0a4116f8df1dd8fcbcc7beabcbb5ff885c1d', '(123) 123-1231', NULL, NULL, '', 1, 'f4259b3a60ab2c45', 1, 'Offline', 'users', 'YYY', 5, '196', 'Anonyme.jpeg'),
(204, 'A', 'A', 'you@mailinator.com', '5cbcac7baf70b7955441a13a0041c2c00b7852e632f004127deabbb4765a9be048199e4a3125d05483d78bb81809e6b4623d7fd34fe58c634145390de337aca9', '(123) 434-3536', 'nullsg', 'Bac Ha Software Co., Ltd.', '193,195,218', 1, '8a7b796004cd8603', 1, 'Offline', 'users', 'Aaa%20bbbb', 9, '', '40095f489a20634438559c071c9e67da_3.jpg'),
(205, 'abc', 'def', 'anhdh.bhsoft+000@gmail.com', 'f8c3e8257be22c0177b41825dcb349cc2fef94d7f5e1dd306e874080a8f93943e93c931097182110b86883a9c0ca1010fb664af6af5b9d21cf0f83110ead7ef5', '(123) 123-1231', NULL, NULL, '', 1, '3175b5691bc67a6a', 1, 'Offline', 'users', 'ghi', 0, '', 'Anonyme.jpeg'),
(206, 'dang', 'nguyen', 'dangnp.pdc@gmail.com', 'f487bc8a68485d42fba4f42dfdfce65bf20ebdc826694d01d39740d3e1f57d40bf814100b5da8da95394ebf9010350a0ee1d6a09bc1e162db101d738dc0b1d3a', '(123) 456-7890', NULL, NULL, '', 0, '4203d44afbee8cf7', 1, 'Offline', 'users', 'dang', 0, '', 'Anonyme.jpeg'),
(207, 'dang', 'nguyen', 'malauca123@gmail.com', '41fb0352c8da83f0125492bcc13f867c44167687618a44115c85226d62ac27ba8e2cb63cb38369864d55c839e2d03f5f22648e3c55e233ff22f861b9820b1d0e', '(123) 456-7890', NULL, NULL, '', 0, 'c959aff7144926d7', 1, 'Offline', 'users', 'dangsfsdf', 0, '', 'Anonyme.jpeg'),
(208, 'dang', 'nguyen', '006278034@coyote.csusb.edu', '2e891bed8bf3ae4b0f3727c1e1e4d9d1fff1c3c5ce7a0641adde975b656bb3e96e29269a62749da125f6373572d8456f568da6830d950dcf94fd6f500291cfa3', '(123) 456-7890', NULL, NULL, '', 0, '65b2d3c4c3d66827', 1, 'Offline', 'users', 'dangsdasdasfsdf', 0, '188', 'Anonyme.jpeg'),
(209, 'adsfasd', 'fasdf', 'asdf@gmail.com', '73f26bad2d6f8f2a76361865738cdd8d463a8db1b88023f33b9a804ebf5801365622cb8b8d3887eb993ce08429ec7b547371811c3b42267aa73eeaafb69a287b', '(123) 456-7890', NULL, NULL, '', 0, 'dc0f737ead88d52b', 1, 'Offline', 'users', 'asdf', 0, '', 'Anonyme.jpeg'),
(210, 'adsfasd', 'fasdf', 'asdf2@gmail.com', '8bfc6dbbb65101d0f98412e484e7e3234d4a79613a3d0b8d86f9da0121b1b6cc76a0c4bddeafda4b43d35b5bdce74830f8229d24e0a6006f2eae288167cc61b5', '(123) 456-7890', NULL, NULL, '', 0, 'fec3a4978263abdd', 1, 'Offline', 'users', 'as3f', 0, '', 'Anonyme.jpeg'),
(211, 'Daniel', 'Nguyen', 'webrtc.bhsoft@gmail.com', 'c35c46cb0cb0d9e17ddf0f346fe67545f70dbf1169cfa04d0cc1e0ee8ee13d67bb3e2dccc5b495c788c118c74bf37cc440d3d46ee6aa5740732a02119d95e33d', '(123) 456-7890', NULL, NULL, '', 1, '52955d442248dcee', 1, 'Offline', 'users', 'dasfasdfasd', 0, '', 'Anonyme.jpeg'),
(212, 'dang', 'dang', 'dangtestpython@gmail.com', 'eb7c99682867326b50847eb144aafd9fe97bf36df00987203b0a5e313573530065340d97d28367da74916764a2a3cf3062fcdb046af3803d730fa4945f9e08e7', '(123) 456-7890', NULL, NULL, '', 1, 'a3f1601731404603', 1, 'Offline', 'users', 'fajskdlfjasjld', 0, '', 'Anonyme.jpeg'),
(213, 'dang', 'dang', 'dangtest12345@mailinator.com', '5c4d6975020c77dc7d55ad1beab356915dc5ff1d3058d341497ab98872e8d209d06fc8594f0caca01fc576acff86c9a344d21bd4eb7f859ab8f234ea5ab14971', '(123) 556-7880', NULL, NULL, '', 1, 'ba3563db978c6d60', 1, 'Offline', 'users', 'jfdaslkjflkas', 0, '', 'Anonyme.jpeg'),
(214, 'fasdf', 'asdfasd', 'fasdfasdf@gamai.com', '442e984cec94b4edd6a0b5af4d347a1d552941d96783da12b4e023566592fc2d0684aba9d73b74450d36630297060b85cdb58954476eb628575911172b557751', '(123) 455-6789', NULL, NULL, '', 0, 'd889d0a2996633dc', 1, 'Offline', 'users', 'fasdf', 0, '', 'Anonyme.jpeg'),
(215, '111', '222', 'anhdh.bhsoft+01@gmail.com', '5e6d9c2fa2b96f5b520fdde4045cdc19ed6a9865840107b03a38c1fc6765116fdf09bf414a513088bfffabe17530d3fe4b5e8585a01eede4342fcdf0cb0e49bc', '(123) 123-1231', NULL, NULL, '', 1, '67aca8d8cadadb51', 1, 'Offline', 'users', '333', 0, '', 'Anonyme.jpeg'),
(216, 'Nguyen%20Luu%20Huong', 'Tra', 'Tranlh@mailinator.com', '09c2b19e3dc7ac3097b48a752efe4aaee512708d13c9c8202fe3323410ac25af953c43e5a9ff0a63d1821837508ba9e48346816cf1fad22b7eab8613039b3c04', '(554) 356-3465', '%20gfsdggfdgdf%20hdhfh', 'company lk flsd fjsdf sfs', '195,218,223,221,228,171', 1, '4d2263f9b5d9bde1', 1, 'Away', 'users', 'Tra%20Tra%20Test%20f', 16, '', 'ac6accf70ed30737d014e9ec1ab16d71_logo.jpg'),
(217, '12%2023', '123%20343', 'anhdh.bhsoft+02@gmail.com', '718a1204a78eeaaffbb5a3f07f9ddcfd2168f6d4cabf3b6b89fef6de450d449dd5d53d3554b5eefe7501f87077b268aba3d7686175aa443b9ea6d758df5da9a3', '(123) 123-2131', NULL, NULL, '', 0, '7ec36c700bf3bdd9', 1, 'Offline', 'users', 'Umasou%20123', 0, '', 'Anonyme.jpeg'),
(218, 'Nguyen%20', 'Nguyen%20', 'Helen@mailinator.com', '0922aa194ec8277110e73d5da9225292611eddf7fe7d8961ee73f114759bbab88c0dcb6697e0bf6e46285e323ea6fe3bbd381df9eb924d7cf9987c5bc8af612e', '(123) 234-4534', NULL, NULL, '204,216,223', 1, '2c619a23d742d4d1', 1, 'Offline', 'users', 'Nguyen%20Nguyen%20', 7, '', 'c6c4779b02b29f524d5a315aeeb317bf_1.jpg'),
(219, '213', '123', 'anhdh.bhsoft+03@gmail.com', '1cfe2bab418a888c49b49894e5aebc6b7ff5e4bf9612f1b2d85ba67387e9422d0afec8f276faa4b30eb9b99f1655bbf5a8dffd4b70d5fd19e55e8d39f803d66f', '(123) 123-1231', NULL, NULL, '', 0, '6f717ff0c46fea7e', 1, 'Offline', 'users', 'Beerus%20%20Sama', 0, '', 'Anonyme.jpeg'),
(220, 'Minh%20', 'Anh%20', 'thu123@mailinator.com', '265c4136f895429ba0183b8f190f4236b3020a9055d89a68606871880b04ba593015b1c202a69328cf2172d04fd2c3f83bfd8a41c2c72f82b80c3dbad213c0a7', '(123) 143-2423', NULL, NULL, '', 1, '42f11fd8fecb63ce', 1, 'Offline', 'users', 'Anh%20', 3, '', 'Anonyme.jpeg'),
(221, 'Tuan%20', 'Anh%20', 'thu132@mailinator.com', 'c1cf2187637a4702d5d229f020a6a11a45a7fdcce0e6edba3b3e0207fa9690c6be8cb2eb7f57b362bfdb0171b7f603bb8479845d353f78e89b123c8caf756b06', '(211) 312-4235', NULL, NULL, '216', 1, 'a54d688eba481ec2', 1, 'Offline', 'users', 'T.Anh', 5, '', 'Anonyme.jpeg'),
(222, 'dh%20', 'anh', 'anhdh.bhsoft+@gmail.com', '73cf387a4b7d44f236589e4cd846e3f34069b835ee3280128aac1b808d557bf29f63742db9ccb2fcc573ae2e1d5f3809e8b72ad8a1e657e06b071f3e328a8086', '(123) 123-8888', 'null', 'BHsoft', '228', 1, '980727f7d7b9ae72', 1, 'Online', 'users', '%EC%97%AC%EC%B9%9C', 76, '', '68e52730323f63a48b284b0a193264dd_download.jpg'),
(223, 'Thu', 'Thu%20Nguyen%20', 'thu@mailinator.com', '9ad892131571ec28b12b6598c58010cb91ae7dee9fc263902ef995b7e560f3411416ca1673660fe92b2fdd0aa76e6c48a54efc0c728ce940999e74f9de6e2087', '(123) 243-5365', 'null', 'Bac Ha Software Co., Ltd.', '216,227,218,228', 1, 'cbdd03b964829ea7', 1, 'Online', 'users', 'thu12', 5, '', 'f606f1a43658abb6cd05765e88b1f2aa_3.jpg'),
(224, 'dasdas', 'dasdas', 'bhmyemail@mailinator.com', '2d290311f267754c90fcee4d9635672735b56592866da30aeccf5bed2cc8088147df43a22ecc21e408a6afd5e059733c93a2e2a1f7d104f1dfbed4cf158e501b', '(124) 354-6354', NULL, NULL, '', 0, 'aeeef7647a4e5dd1', 1, 'Offline', 'users', 'asdasdzxccas', 0, '', 'Anonyme.jpeg'),
(225, 'dasdas', 'dasdas', 'vxzcvzxcvzxcv@mailinator.com', 'c65c31a1e7c13fce623356fe7a117fdacbfae1e5f3418faa5563d8c51f9aa16cb636d7614e82914ac904d85447ff3bfbb06e3010fb2a45d63d962147c1287a8f', '(124) 354-6354', NULL, NULL, '', 0, '862d7ba313bef8dd', 1, 'Offline', 'users', 'asdas%20dzxccas', 0, '', 'Anonyme.jpeg'),
(226, 'dasdas', 'dasdas', 'vxzcvzxcvzxcvccc@mailinator.com', 'c2e792eeceb6a2477bad0a884a0ecaf1a3deb3c305b74a584beb9d348ffe373ac3ea747532e199ffb917f64419ca60b00622cbbfabfcce3ba5462bc4d6f325c9', '(124) 354-6354', NULL, NULL, '', 1, '3a8d4410b7036797', 1, 'Offline', 'users', 'C%C3%B3%20d%E1%BA%A5u%20name', 0, '', 'Anonyme.jpeg'),
(227, 'Ngoc', 'Hong', 'Ngoch@mailinator.com', '1fb54ff402a75666cd1c996e574a532bb745115de30b8c65708f0798111a66f632d5c39e2af8ac2bece6da2aa666fe5eed0286f9fa6577410e6c1421dc65ba15', '(463) 465-6547', NULL, NULL, '223', 1, '16f7895379a5e6c1', 1, 'Offline', 'users', 'Hong%20ngoc%20jkkk', 3, '', 'Anonyme.jpeg'),
(228, '%EB%82%A8', '%EC%B9%9C', 'anhdh.bhsoft++@gmail.com', 'f3fd62c4ab62ed706e9d5b833633b0fd86749521774c3ee5d45e395d143828fe1c7e7ed6ced13ec923c3f748c40a3957b3c409ace9152d38fea18ae6ed31f11d', '(123) 123-1231', 'null', 'BAC HA SOFTWARE CO., LTD.', '223,216,171,188,222', 1, '8d23126dbff83da0', 1, 'Offline', 'users', '%EB%82%A8%EC%B9%9C', 78, '', 'eac4573ced8a184dd075defd7e47fff2_1.jpg'),
(229, 'dang', 'nguyen', 'mkfmdkmfkd@mailinator.com', 'a30919089e05d09e2ce1a5ae41652a966e7fd5b61665bf7a674d8c47901cfde189ca1ef193bcfd70f067d69ba735e3f1ba2103886754fe58eb587865e29e9482', '(123) 454-3654', NULL, NULL, '', 0, '2920a19a6aa8401e', 1, 'Offline', 'users', 'some%20name', 0, '', 'Anonyme.jpeg'),
(230, 'fasdfasdf', 'asdfasdf', '', '865ee34f63b655dbea5ac6645f4137e3719017d5a89b2a18abea83e7a7f46b31a6118e6f65d3b8bafd0dabef56124db753e83f07067b57ad1ecc2cfc50fde9f2', '(123) 345-6789', NULL, NULL, '', 0, 'f2773052356a86ef', 1, 'Offline', 'users', 'asdfasdfasdfd', 0, '', 'Anonyme.jpeg'),
(231, 'fasdfasdf', 'asdfasdf', 'dangnp.bh312312312soft@gmail.com', '730374844100ee08688c86a08eac7d690ed5d2038d4d88085142b5667b0beb6d56a39d07d44c6eed4002ba46335491f89415ee78253800c3386a600d6dd56f1c', '(123) 432-5364', NULL, NULL, '', 0, '019152f9114d911d', 1, 'Offline', 'users', 'asdfasd', 0, '', 'Anonyme.jpeg'),
(232, 'fasdfasdf', 'asdfasdf', 'dangnp.bh31czxczxczx2312312soft@gmail.com', 'c4335005ef94bdc08921eb821756d2dd0075c71d982b81abb17833e3f78da83c31bd806f307ddffe7159e55041f8f990894fc1a311a22c4bdb4f7bfb3025556f', '(123) 432-5364', NULL, NULL, '', 0, 'abb2ea4f290a325b', 1, 'Offline', 'users', 'asdwwwwasd', 0, '', 'Anonyme.jpeg'),
(233, 'fasdfasd', 'fasdfasd', 'zxczxczxvvvvzx@mailinator.com', '3468809527b7e152a01264e4184bd1377ffa5aed71c30754d6b5c9446acdea81d07d6eebda75f9086364cd30c0e521e979e97be67bc95435db741d9ac65dc0ad', '(213) 423-4654', NULL, NULL, '', 0, 'f9f8c69b09eaa48e', 1, 'Offline', 'users', 'fasdfsadf', 0, '', 'Anonyme.jpeg'),
(234, 'fasdfklasdj', 'jklfasdjflkas', 'zxczxczxvvvvzxdasdas@mailinator.com', '997b6ffc03b6e6813b5a8b7d1d10c82533ab80a7504a50835f3d99e99238df32be830f162332bbcd037cfa5a63d79ded46345e6d3f52f89d3e2e299d9135bf49', '(124) 352-4635', NULL, NULL, '', 0, 'b30f8758908f4407', 1, 'Offline', 'users', 'fasdlkfmxcnzv', 0, '', 'Anonyme.jpeg'),
(235, 'fasdfasd', 'fasdfas', 'fasdfasdf@gmail.com', 'd0c14788f8d54aef349eafe4479aaed0df1834b754e419eda089a465012fd0e73173ced5602c6ba09a909c6577f86fb634e9baf88470764365ffb5f5e66db9a6', '(143) 253-5676', NULL, NULL, '', 0, '7dbde092db8a6201', 1, 'Offline', 'users', 'dfasdfasdf', 0, '', 'Anonyme.jpeg'),
(236, 'asda', 'sdas', '1432564e7rtuyfik@gmail.com', '5c85d39d4d4f61e4c41ef0c7e4713d5bfe98721cc880f31214c9f04b950c380e6e39dc88422f15a930ce66ffbbe8cb1a8ddb7198cd8d55201e6820a24c52e1f2', '(122) 435-6797', NULL, NULL, '', 0, '66efb4f3ff15776e', 1, 'Offline', 'users', 'dasdasdas', 0, '', 'Anonyme.jpeg'),
(237, 'dan', 'dan', 'dang1234@mailinator.com', 'abf77dc55170c4dcca1e94acb3873b20100a23124155e95d469aad5b28a002d344b3319faf87f865d4a62c2533da4ee0a0344663183d80ec03175a1963b65fd5', '(124) 354-3657', NULL, NULL, '188', 1, 'd3cc987929115448', 1, 'Offline', 'users', 'dan', 10, '', 'Anonyme.jpeg'),
(238, 'fasdfasd', 'fasd', 'something1asdf@mailinator.com', '25a602089ae805f04e3232ee3f98a378aa099651dc4fd0c5a36673c3e91a2a6e47ba45da69b5709501bdd877e3c2ccb0066f4819cfe15c0c7a4ec387aa3c3990', '(124) 325-3464', NULL, NULL, '', 0, 'c2d9ca9f13055ceb', 1, 'Offline', 'users', 'fasdfasd', 0, '', 'Anonyme.jpeg'),
(239, 'fasdfasd', 'fasd', 'jklsdjfklsd@mailinator.com', '221ff4cda6d008c85aa4c6eb5b1cb0b79b7d8b8ed8b06edf3011b611d418d6427cabdfc4953ce76dd033dbd6475d24f1254efffd0f45b8bd46fd0ebcce15c5b6', '(124) 325-3464', NULL, NULL, '', 0, 'bdf4dda6cf144fc1', 1, 'Offline', 'users', 'c%C3%B3%20ch%C3%A0ng%20chai%20vi%E1%BA%BFt%20n%C3%AAn%20c%C3%A2y', 0, '', 'Anonyme.jpeg'),
(240, 'Quang', 'Trung', 'trungtong.bhtech+004@gmail.com', '67b3f061201128d2a5054c61ae00c4feb53d6d6a740c611e9ee6927311351bdc490329ea09636095558fd41e133c3b33b246ef4b6f8153a4416b7577714859a0', '841222222222', NULL, 'BHTech', '', 0, 'b2f99e6671a0905f', 1, 'Offline', 'users', 'Quang_Trung', 0, '', 'Anonyme.jpeg'),
(241, 'Hi', 'Ha', 'anhdh.bhsoft+11@gmail.com', '8bce0d2d0f4fbb4aa7d5065c995b6c064fef99ca3ff41632250f4239d62fb03e75560fd3714b09d249cf6d3be55451b99bd59d74a8552f998e114a78a635e0a7', '(123) 456-789', 'null', 'ád', '', 1, '624e0b3fb131a73f', 1, 'Offline', 'users', 'HihaHiha', 8, '', 'Anonyme.jpeg'),
(242, 'Thuy', 'Phan', 'thuypt.dcn@gmail.com', 'd5e89325be9a918cda15dce7287c0d604089006e7ae43eb79d09eb9495387a362f1ebe165eda67d029517155d1e41154e804b2f1121f6c21752cfe7e0083c91e', '(096) 306-1424', NULL, NULL, '', 1, 'ada7766c420b488a', 1, 'Offline', 'users', 'Thuypt', 4, '', 'Anonyme.jpeg');

-- 
-- Dumping data for table chat
--
INSERT INTO chat VALUES
(333, '1:57', '1:57', '', '1'),
(334, '1:27', '1:27', '', '1'),
(335, '1:26', '1:26', '', '1'),
(339, '26:27', '26:27', '', '26'),
(340, '27:57', '27:57', '', '27'),
(341, '1:2:26:27:57', 'Vietnam Vie', '', '57'),
(342, '129:132', '129:132', 'undefined,', '132'),
(343, '129:131', '129:131', '', '129'),
(344, '57:149', '57:149', 'Coconuts,', '57'),
(345, '26:57', '26:57', '', '26'),
(346, '57:152', '57:152', 'aaa,', '57'),
(347, ':152', ':152', '', '152'),
(348, '57:155', '57:155', 'CorentinA,', '155'),
(349, '26:27:57', 'Presentation', '', '57'),
(350, '1:2:57', 'Test2', '', '57'),
(351, '1:126', '1:126', '', '126'),
(352, '26:126', '26:126', '', '126'),
(353, '58:126', '58:126', '', '126'),
(354, '1:26:27:57:126', 'BHSoft', 'Coczer,', '1'),
(355, ':126', ':126', '', '126'),
(356, '126:129', '126:129', '', '126'),
(358, '58:157', '58:157', '', '58'),
(359, ':158', ':158', '', '158'),
(360, '126:157', '126:157', '', '157'),
(361, '157:158', '157:158', '', '157'),
(362, '129:157', '129:157', '', '157'),
(363, '161:162', '161:162', '', '162'),
(364, ':161', ':161', '', '161'),
(365, '129:130:157:161', 'gr', '', '129'),
(366, '129:161', '129:161', '', '129'),
(367, '127:130', '127:130', '', '127'),
(368, '127:132', '127:132', '', '127'),
(369, '158:161', '158:161', 'Quang,', '158'),
(370, '126:129:130:157:161', 'Group A', '', '129'),
(371, '129:130', '129:130', 'zeno sama,', '130'),
(372, '126:126:126:126:126:126:126:126:126:129:161:161:161:161:161:161:161:161:161:161:161:161', 'Group test', '', '129'),
(373, '158:162', '158:162', '', '158'),
(374, '129:158', '129:158', '', '158'),
(375, '126:129:130:131', 'group New', '', '129'),
(376, '129:161:162', 'jikhijuhiuhiuh', '', '161'),
(377, '::::::::::::::::::::129:130:131:131:131:132:161:161', 'test', '', '129'),
(379, '129:130:131', '234234234', '', '129'),
(380, '129:130:131', '123123', '', '129'),
(381, '129:130:131', '12341', '', '129'),
(383, '129:131:158:158:161', 'New UI of Group', '', '129'),
(386, '129:130:158', '2233233', '', '129'),
(389, '129:130:131', 'fdsfs', '', '129'),
(390, ':169', ':169', '', '169'),
(391, '169:170', '169:170', '', '170'),
(393, '58:124', '58:124', '', '58'),
(394, '58:124:157', 'test', '', '58'),
(395, '169:171', '169:171', 'user_1,', '171'),
(421, '130:132', '130:132', '', '132'),
(426, '129:133', '129:133', '', '133'),
(441, '130:133', '130:133', '', '133'),
(442, '133:182', '133:182', '', '182'),
(443, '133:184', '133:184', '', '184'),
(445, ':132', ':132', '', '132'),
(448, '131:133', '131:133', '', '131'),
(449, '129:184', '129:184', '', '129'),
(450, '127:131', '127:131', '', '131'),
(451, '131:184', '131:184', '', '184'),
(452, '129:170', '129:170', 'user_3,', '129'),
(453, '130:131', '130:131', '', '131'),
(454, '131:132', '131:132', '', '131'),
(455, '118:132', '118:132', '', '132'),
(456, '132:133', '132:133', '', '132'),
(463, '132:184', '', '', '131'),
(464, '127:127:127:127:127:127:127:129', '', '', '131'),
(465, '127:127:127:127:127:127:127:129:131', 'New UI of Group', '', '131'),
(466, '127:127:127:127:127:127:127:129:131', 'tsfhg', '', '131'),
(468, '127:127:127:127:127:127:127:129:131', 'tsfhg', '', '131'),
(469, '127:127:127:127:127:127:127:129:131', 'tsfhg', '', '131'),
(470, '127:127:127:127:127:127:127:129:131', 'tsfhg', '', '131'),
(471, '127:127:127:127:127:127:127:129:131', 'tsfhg', '', '131'),
(472, '127:127:127:127:127:127:127:129:131', 'tsfhg', '', '131'),
(522, '184:185', '184:185', 'Anh%20Anh,', '185'),
(524, '132:170', '132:170', '', '170'),
(525, '132:182', '132:182', 'Thunt,', '132'),
(526, '132:184', '132:184', '', '132'),
(527, '182:184', '182:184', 'Thunt,', '184'),
(552, '129:182', '129:182', 'Thunt,', '182'),
(643, '131:182', '131:182', '', '182'),
(645, ':182', ':182', '', '182'),
(646, '1:136', '1:136', 'Adelin_ARNOU,', '136'),
(649, ':', 'Test group', 'user_1,', '170'),
(654, ':', 'Test 43', '', '171'),
(656, '182', 'Test1', '', '132'),
(657, '131:132:182', 'ahihi', '', '184'),
(658, ':::', '', '', '184'),
(662, ':', '159', '', '185'),
(664, ':', '1321321', '', '185'),
(667, '182:185', '182:185', '', '185'),
(669, ':', '123', '', '184'),
(674, '129', '234234234', '', '184'),
(684, ':', '888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888', '', '184'),
(685, ':', '888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888', '', '184'),
(693, '184:186', '184:186', '', '184'),
(702, '169:182', '169:182', '', '182'),
(717, '180', '180', '', '179'),
(719, ':188', ':188', '', '188'),
(725, '132:185', '132:185', '', '185'),
(734, '182:193', '182:193', 'Thunt.bhsoft,', '193'),
(735, ':192', ':192', '', '192'),
(736, '192:193', '192:193', 'Thunt.bhsoft,', '192'),
(738, '171:192', '171:192', '', '192'),
(739, '193:201', '193:201', '', '201'),
(740, '193:204', '193:204', '', '204'),
(742, '188:192', '188:192', '', '192'),
(743, ':195', ':195', '', '195'),
(744, '192:195', '192:195', '', '195'),
(745, '193:195', '193:195', 'Thunt.bhsoft,', '193'),
(746, '192:193:195:204', 'new group', '', '193'),
(767, ':171', ':171', '', '171'),
(770, '188:192:193:195:196', '123xZXCxXx', '', '192'),
(773, ':129', ':129', '', '129'),
(774, '129:195', '129:195', '', '129'),
(775, '58:126:129', 'Testing WebRTC App', 'hong%20Ngoc,', '126'),
(776, '129:192', '129:192', 'hong%20Ngoc,', '129'),
(777, ':157', ':157', '', '157'),
(778, '157:195', '157:195', 'quantr.bhtech,', '195'),
(780, '129:188', '129:188', '', '188'),
(781, '188:195', '188:195', '', '188'),
(782, '192:196', '192:196', 'bloblo,', '196'),
(783, '204:218', '204:218', 'Aaa,Nguyen%20Nguyen%20,', '218'),
(784, ':216', ':216', '', '216'),
(785, '216:218', '216:218', 'Nguyen%20Nguyen%20,', '218'),
(786, '195:216', '195:216', '', '216'),
(788, '216:223', '216:223', '', '216'),
(789, ':223', ':223', '', '223'),
(790, '218:223', '218:223', 'Nguyen%20Nguyen%20,', '223'),
(791, '223:227', '223:227', '', '223'),
(795, '223:228', '223:228', '', '223'),
(796, '216:228', '216:228', 'Heart%20Umasou,', '216'),
(805, '171:228', '171:228', '', '228'),
(815, '188:228', '188:228', '', '188'),
(818, '171:216', '171:216', '', '216'),
(819, '195:204', '195:204', '', '195'),
(820, '129:188:189', 'whatever', '', '188'),
(823, '129:188:189', 'dasdas', '', '188'),
(830, '129:188:189', 'fdsafsdf', '', '188'),
(831, '188:189', '188:189', '%C4%90%C4%83ng%201,', '189'),
(832, '188:237', '188:237', '%C4%90%C4%83ng%201,', '237'),
(836, '179:180', '179:180', '123456,', '179'),
(837, '179:181', '179:181', '', '179'),
(838, ':170', ':170', '', '170'),
(850, '222:228', '222:228', '%EC%97%AC%EC%B9%9C,', '228');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;