name: my_travel
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  # loading
  flutter_spinkit: "^2.1.0"
  # slide show
  carousel_slider: ^1.3.0
  flutter_rating_bar: 3.0.0
  # sign in gg
  google_sign_in: ^4.0.14
  rxdart: ^0.18.0
  http: ^0.12.0
  toast: ^0.1.5
  flutter_money_formatter: ^0.8.3
  money: ^0.2.1
  flutter_picker: ^1.1.0
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  #toast
  fluttertoast: ^3.1.3
  #luu tru
  shared_preferences: ^0.5.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/